debug: false
server:
  port: 8080
  servlet:
    context-path: /v1/api

---
spring:
  profiles: PROD
  datasource:
    url: jdbc:mysql://localhost:3306/soma

  jpa:
    hibernate:
      ddl-auto: update
      dml-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---

spring:
  profiles: LOCAL
  datasource:
    url: jdbc:mysql://localhost:3306/soma
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dml-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---



